name: Deploy Jill

on:
  workflow_run:
    workflows: [Build Apps CD]
    branches: [main]
    types: [completed]
    push:
      branches: [main]
      paths:
        - 'apps/jill/**'
        - 'libs/types/**'

jobs:
  deploy_jill:
    name: Deploy Jill
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd ./pet-documents
            sh ./scripts/deploy-jill.sh
